'use client';
import {useState,useEffect} from 'react';

const roleLabel=role=>role==='admin'?'Company Administrator':role==='branch'?'Branch Staff':'Company Staff';
function RoleOptions({platform}){return <>{platform&&<option value="admin">Company Administrator</option>}<option value="staff">Company Staff</option><option value="branch">Branch Staff</option></>}
function BranchOptions({branches}){return <><option value="">All permitted branches</option>{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</>}
function ModuleChoices({selected,onChange,companyModules,moduleLabels,busy}){return <div className="module-settings-grid">{Object.entries(moduleLabels).filter(([key])=>key!=='import').map(([key,label])=><label key={key} className={selected.includes(key)?'active':''}><input type="checkbox" disabled={busy||!companyModules.includes(key)} checked={selected.includes(key)&&companyModules.includes(key)} onChange={e=>onChange(e.target.checked?[...selected,key]:selected.filter(value=>value!==key))}/><span>{label}{!companyModules.includes(key)&&' (disabled)'}</span></label>)}</div>}

export default function AccessManagement({invite,setInvite,branches,staff,busy,createStaff,patchStaff,deleteStaff,platform,companyModules,moduleLabels,portal,actorId}){
 const [showCreate,setShowCreate]=useState(false),[search,setSearch]=useState(''),[roleFilter,setRoleFilter]=useState('all');
 const matching=staff.filter(person=>(roleFilter==='all'||(roleFilter==='admin'?person.role==='admin':person.role!=='admin'))&&`${person.full_name||''} ${person.email||''}`.toLowerCase().includes(search.trim().toLowerCase()));
 const available=branches.filter(branch=>branch.is_active);
 return <div className="settings-card access-management"><div className="access-header"><div><span className="access-eyebrow">ACCESS MANAGEMENT</span><h3>People and permissions</h3><p>Manage accounts, branch access and the tools each person can use.</p></div><button className="primary" type="button" disabled={busy} onClick={()=>setShowCreate(value=>!value)}>{showCreate?'Close form':'+ Add account'}</button></div>
 <div className="access-summary"><span><b>{staff.length}</b> Accounts</span><span><b>{staff.filter(person=>person.is_active).length}</b> Active</span><span><b>{staff.filter(person=>person.role==='admin').length}</b> Administrators</span>{portal&&<a href={`https://${portal}`} target="_blank" rel="noreferrer">Company portal ↗</a>}</div>
 {showCreate&&<form className="access-create" onSubmit={async event=>{if(await createStaff(event))setShowCreate(false)}}><h4>Create an account</h4><p>Set a password directly. No invitation email will be sent.</p><div className="access-form-grid"><label>Full name<input required value={invite.full_name} onChange={e=>setInvite({...invite,full_name:e.target.value})}/></label><label>Email address<input required type="email" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></label><label>Role<select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})}><RoleOptions platform={platform}/></select></label><label>Branch<select required={invite.role==='branch'} value={invite.branch_id} onChange={e=>setInvite({...invite,branch_id:e.target.value})}><BranchOptions branches={available}/></select></label><label className="access-wide">Initial password<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={invite.password} onChange={e=>setInvite({...invite,password:e.target.value})} placeholder="At least 12 characters"/></label></div>
 {invite.role!=='admin'&&<fieldset className="access-module-fieldset"><legend>Module access</legend><ModuleChoices selected={invite.staff_modules||companyModules.filter(key=>key!=='import')} onChange={modules=>setInvite({...invite,staff_modules:modules})} companyModules={companyModules} moduleLabels={moduleLabels} busy={busy}/></fieldset>}
 <div className="access-form-footer"><small>Access is limited to this company’s dedicated portal.</small><button className="primary" disabled={busy}>{busy?'Saving…':'Create account'}</button></div></form>}
 <div className="access-list-toolbar"><input type="search" aria-label="Search accounts" placeholder="Search name or email" value={search} onChange={event=>setSearch(event.target.value)}/><div role="group" aria-label="Account role filter">{[['all','All accounts'],['admin','Administrators'],['staff','Staff']].map(([value,label])=><button type="button" key={value} className={roleFilter===value?'active':''} onClick={()=>setRoleFilter(value)}>{label}</button>)}</div></div><div className="access-account-list">{matching.length?matching.map(person=><AccountCard key={person.id} person={person} branches={available} platform={platform} actorId={actorId} busy={busy} companyModules={companyModules} moduleLabels={moduleLabels} patchStaff={patchStaff} deleteStaff={deleteStaff}/>):<div className="empty-soft">No accounts match. Change the filters or add an account.</div>}</div></div>
}
function AccountCard({person,branches,platform,actorId,busy,companyModules,moduleLabels,patchStaff,deleteStaff}){
 const [editing,setEditing]=useState(false),[confirmDelete,setConfirmDelete]=useState(false),[password,setPassword]=useState('');
 const [draft,setDraft]=useState(person),[modules,setModules]=useState(person.staff_modules||companyModules.filter(key=>key!=='import'));
 useEffect(()=>{setDraft(person);setModules(person.staff_modules||companyModules.filter(key=>key!=='import'))},[person,companyModules]);
 const canEdit=!person.is_platform_super_admin&&(platform||person.role!=='admin');
 const branch=branches.find(value=>value.id===person.branch_id)?.name||'All permitted branches';
 return <article className="access-account"><header><div className="access-person"><span className="access-avatar">{(person.full_name||'U').slice(0,1).toUpperCase()}</span><div><strong>{person.full_name||'Unnamed account'}</strong><small>{person.email}</small></div></div><span className={`access-state ${person.is_active?'active':''}`}>{person.is_active?'Active':'Inactive'}</span></header><div className="access-person-meta"><span>{roleLabel(person.role)}</span><span>{branch}</span><span>{person.role==='admin'?'Company management access':Array.isArray(person.staff_modules)?`${person.staff_modules.length} modules`:'Company defaults'}</span></div>
 {canEdit?<div className="access-account-actions"><button className="secondary" disabled={busy} onClick={()=>setEditing(value=>!value)}>{editing?'Close editor':'Edit account'}</button><button className="secondary" disabled={busy||person.id===actorId} onClick={()=>patchStaff(person.id,{is_active:!person.is_active})}>{person.is_active?'Deactivate':'Activate'}</button><button className="access-danger" disabled={busy||person.id===actorId} onClick={()=>setConfirmDelete(true)}>Delete</button></div>:<p className="access-locked">Administrator accounts are managed by the platform owner.</p>}
 {editing&&canEdit&&<div className="access-editor"><form onSubmit={async e=>{e.preventDefault();if(await patchStaff(person.id,{full_name:draft.full_name,email:draft.email,role:draft.role,branch_id:draft.branch_id||null}))setEditing(false)}}><div className="access-form-grid"><label>Full name<input required value={draft.full_name||''} onChange={e=>setDraft({...draft,full_name:e.target.value})}/></label><label>Email address<input required type="email" value={draft.email||''} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Role<select disabled={person.id===actorId} value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><RoleOptions platform={platform}/></select></label><label>Branch<select required={draft.role==='branch'} value={draft.branch_id||''} onChange={e=>setDraft({...draft,branch_id:e.target.value})}><BranchOptions branches={branches}/></select></label></div><div className="access-form-footer"><button className="primary" disabled={busy}>Save account</button></div></form>
 {person.role!=='admin'&&<details className="staff-module-editor"><summary>Module access</summary><ModuleChoices selected={modules} onChange={setModules} companyModules={companyModules} moduleLabels={moduleLabels} busy={busy}/><div className="access-form-footer"><button className="secondary" disabled={busy} onClick={()=>patchStaff(person.id,{staff_modules:null})}>Company defaults</button><button className="primary" disabled={busy} onClick={()=>patchStaff(person.id,{staff_modules:modules})}>Save modules</button></div></details>}
 <details className="staff-module-editor"><summary>Set / reset password</summary><form className="staff-password-form" onSubmit={async e=>{e.preventDefault();if(await patchStaff(person.id,{new_password:password}))setPassword('')}}><label>New password<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>Save password</button><small>Replaces the password without sending an email.</small></form></details></div>}
 {confirmDelete&&<div className="access-delete-confirm" role="alert"><strong>Delete {person.full_name}’s account?</strong><p>Sign-in access will be removed. Case, payment and custody records will remain.</p><div><button className="secondary" disabled={busy} onClick={()=>setConfirmDelete(false)}>Cancel</button><button className="access-danger" disabled={busy} onClick={()=>deleteStaff(person.id)}>Delete account</button></div></div>}
 </article>
}
