'use client';
import {useEffect,useRef,useState} from 'react';
import {matchServices} from '../lib/catalogSearch';
export default function BulkServicePicker({services,onClose,onAdd,onQuickAdd}){
 const [q,setQ]=useState(''),[selected,setSelected]=useState([]);const root=useRef(null);
 useEffect(()=>{const prev=document.activeElement;root.current?.querySelector('input')?.focus();const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=[...root.current.querySelectorAll('input,button')].filter(x=>!x.disabled);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0]?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prev?.isConnected&&prev.focus()}},[]);
 const add=s=>setSelected(a=>a.some(x=>x.id===s.id)?a.map(x=>x.id===s.id?{...x,quantity:Number(x.quantity)+1}:x):[...a,{...s,quantity:1,rate:Number(s.service_charge??s.base_price??0),government_fee:Number(s.government_fee||0)}]);
 return <div className="business-overlay"><section ref={root} className="business-dialog bulk-dialog" role="dialog" aria-modal="true" aria-label="Add items in bulk"><header><h2>Add items in bulk</h2><button type="button" className="business-close" aria-label="Close" onClick={onClose}>×</button></header><div className="bulk-columns"><section><div className="picker-input"><input aria-label="Search bulk services" placeholder="Search services…" value={q} onChange={e=>setQ(e.target.value)}/><button type="button" className="secondary icon-action" title="New service" aria-label="New service" onClick={onQuickAdd}>＋</button></div><div className="bulk-scroll">{matchServices(services,q).slice(0,100).map(s=><button type="button" className="bulk-service" key={s.id} onClick={()=>add(s)}><strong>{s.name}</strong><span>{Number(s.base_price||0).toFixed(2)} ＋</span></button>)}</div></section><section><h3>Selected items <small>{selected.length} · Qty {selected.reduce((n,x)=>n+Number(x.quantity),0)}</small></h3><div className="bulk-scroll">{selected.map(s=><div className="bulk-selected" key={s.id}><strong>{s.name}</strong><label>Qty<input type="number" min=".01" max="10000" step=".01" value={s.quantity} onChange={e=>setSelected(a=>a.map(x=>x.id===s.id?{...x,quantity:e.target.value}:x))}/></label><label>Rate<input type="number" min="0" max="99999999" step=".01" value={s.rate} onChange={e=>setSelected(a=>a.map(x=>x.id===s.id?{...x,rate:e.target.value}:x))}/></label><button type="button" aria-label={'Remove '+s.name} onClick={()=>setSelected(a=>a.filter(x=>x.id!==s.id))}>×</button></div>)}{!selected.length&&<p>Select services from the catalogue.</p>}</div></section></div><footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="button" className="primary" disabled={!selected.length||selected.some(x=>!(Number(x.quantity)>0)||!Number.isFinite(Number(x.rate))||Number(x.rate)<0||Number(x.quantity)>10000||Number(x.rate)>99999999)} onClick={()=>onAdd(selected.map(x=>({...x,service_charge:Number(x.rate)})))}>Add {selected.length} items</button></footer></section></div>
}
