'use client';
import {useEffect,useId,useState} from 'react';
import {supabase} from '../lib/supabase';
// Short-lived result cache accelerates repeat lookups; server RLS remains authoritative.
const cache=new Map();
supabase.auth.onAuthStateChange(()=>cache.clear());
export default function CustomerPicker({organizationId,value,onSelect,onQuickAdd}){
 const [q,setQ]=useState(''),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[open,setOpen]=useState(false);const listId=useId();
 useEffect(()=>{let live=true;setError('');if(!q.trim()||!organizationId){setResults([]);setLoading(false);return}const key=organizationId+':'+q.trim().toLowerCase(),hit=cache.get(key);if(hit&&Date.now()-hit.at<15000){setResults(hit.data);setLoading(false);return}setLoading(true);const timer=setTimeout(async()=>{try{const {data,error}=await supabase.rpc('search_business_customers',{target_org:organizationId,query_text:q.trim(),result_limit:12,result_offset:0});if(!live)return;if(error)throw error;setResults(data||[]);if(cache.size>100)cache.clear();cache.set(key,{at:Date.now(),data:data||[]})}catch{if(live)setError('Customers could not be loaded. Please retry.')}finally{if(live)setLoading(false)}},70);return()=>{live=false;clearTimeout(timer)}},[q,organizationId,retry]);
 return <div className="business-customer-picker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><div className="picker-input"><input role="combobox" aria-expanded={open} aria-label="Search customer name or mobile" aria-controls={listId} value={q} onFocus={()=>setOpen(true)} onChange={e=>{setQ(e.target.value);setOpen(true)}} placeholder={value?'Search to replace customer':'Search customer name or mobile'}/>{onQuickAdd&&<button type="button" className="secondary" aria-label="Quick add customer" onClick={onQuickAdd}>＋</button>}</div>{open&&(q.trim()||onQuickAdd)&&<div id={listId} className="business-picker-results">{q.trim()&&(error?<p role="alert">{error} <button type="button" onClick={()=>{cache.clear();setRetry(n=>n+1)}}>Retry</button></p>:results.map(c=><button type="button" key={c.id} onClick={()=>{onSelect(c);setQ('');setResults([]);setOpen(false)}}><strong>{c.name}</strong><span>{c.mobile||c.email||'Customer'}</span></button>))}{loading&&<small role="status">Searching…</small>}{q.trim()&&!loading&&!error&&!results.length&&<p>No matching customers.</p>}{onQuickAdd&&<button type="button" onClick={()=>{setOpen(false);onQuickAdd()}}>＋ Add customer</button>}</div>}</div>
}
