'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
const cache=new Map();
supabase.auth.onAuthStateChange(()=>cache.clear());
export const customerSeed=q=>/^\+?[\d\s()-]+$/.test(q.trim())?{mobile:q.trim(),name:''}:{name:q.trim(),mobile:''};
async function searchCustomers(org,q,offset=0){const key=org+':'+q.trim().toLowerCase()+':'+offset,hit=cache.get(key);if(hit&&Date.now()-hit.at<15000)return hit.promise;const promise=supabase.rpc('search_business_customers',{target_org:org,query_text:q.trim(),result_limit:30,result_offset:offset}).then(r=>{if(r.error)throw r.error;return r.data||[]});if(cache.size>100)cache.clear();cache.set(key,{at:Date.now(),promise});try{return await promise}catch(e){cache.delete(key);throw e}}
export default function CustomerPicker({organizationId,value,onSelect,onQuickAdd}){
 const [q,setQ]=useState(''),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[open,setOpen]=useState(false),[active,setActive]=useState(0),[more,setMore]=useState(false);const listId=useId(),entering=useRef(false),activeSearch=useRef('');activeSearch.current=organizationId+':'+q;
 useEffect(()=>{let live=true;setError('');setActive(0);if(!organizationId)return;setLoading(true);const timer=setTimeout(async()=>{try{const data=await searchCustomers(organizationId,q);if(live){setResults(data);setMore(data.length===30)}}catch{if(live){setResults([]);setError('Customers could not be loaded. Please retry.')}}finally{if(live)setLoading(false)}},q?70:0);return()=>{live=false;clearTimeout(timer)}},[q,organizationId,retry]);
 function choose(c){onSelect(c);setQ('');setOpen(false)}
 function add(){setOpen(false);onQuickAdd?.(customerSeed(q))}
 async function enter(e){if(e.key==='Escape')setOpen(false);if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(n=>Math.min(results.length-1,n+1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(n=>Math.max(0,n-1))}if(e.key==='Enter'){e.preventDefault();if(entering.current)return;entering.current=true;try{const data=loading?await searchCustomers(organizationId,q):results;if(data.length)choose(data[Math.min(active,data.length-1)]);else if(q.trim()&&!error&&onQuickAdd)add()}catch{setError('Customers could not be loaded. Please retry.')}finally{entering.current=false}}}
 return <div className="business-customer-picker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><div className="picker-input"><input role="combobox" aria-expanded={open} aria-label="Search customer name or mobile" aria-controls={listId} aria-activedescendant={open&&results[active]?listId+'-'+active:undefined} value={q} onFocus={()=>setOpen(true)} onChange={e=>{setQ(e.target.value);setOpen(true)}} onKeyDown={enter} placeholder={value?'Search to replace customer':'Customer name or mobile'}/>{onQuickAdd&&<button type="button" className="secondary icon-action" title="New customer" aria-label="New customer" onClick={add}>＋</button>}</div>{open&&<div id={listId} className="business-picker-results" role="listbox">{error?<p role="alert">{error} <button type="button" onClick={()=>{cache.clear();setRetry(n=>n+1)}}>Retry</button></p>:results.map((c,i)=><button role="option" aria-selected={i===active} id={listId+'-'+i} type="button" key={c.id} onClick={()=>choose(c)}><strong>{c.name}</strong><span>{c.mobile||c.email||'Customer'}</span></button>)}{loading&&<small role="status">Loading customers…</small>}{!loading&&!error&&!results.length&&<p>{q?(onQuickAdd?'No matching customer. Press Enter to add.':'No matching customer.'):'No customers yet.'}</p>}{more&&<button type="button" disabled={loading} onClick={async()=>{setLoading(true);try{const data=await searchCustomers(organizationId,q,results.length);if(activeSearch.current===organizationId+':'+q){setResults(r=>[...r,...data]);setMore(data.length===30)}}catch{setError('Customers could not be loaded. Please retry.')}finally{if(activeSearch.current===organizationId+':'+q)setLoading(false)}}}>Load more</button>}{onQuickAdd&&<button type="button" title="New customer" aria-label="New customer" className="picker-quick-add" onClick={add}>＋</button>}</div>}</div>
}
