'use client';
import {useEffect,useRef,useState} from 'react';
export default function PdfPreviewModal(){
 const [doc,setDoc]=useState(null),[full,setFull]=useState(false),[scale,setScale]=useState(1),[fit,setFit]=useState(true),[viewport,setViewport]=useState(900),[height,setHeight]=useState(1123),[ready,setReady]=useState(false);const frame=useRef(null),root=useRef(null),area=useRef(null),current=useRef(null);
 const close=()=>{current.current=null;setDoc(null)};
 useEffect(()=>{const listener=e=>{const d=e.detail;if(d.action==='close-all'){close()}else if(d.action==='open'){current.current=d.id;setDoc({id:d.id,title:d.title});setReady(false);setFull(false);setFit(true)}else if(d.id===current.current){if(d.action==='close')close();else if(d.action==='error')setDoc(x=>({...x,error:d.message}));else if(d.action==='configure')setDoc(x=>({...x,...(d.title?{title:d.title}:{}),...(d.templates?{templates:d.templates,selectedTemplate:d.selectedTemplate,onSelectTemplate:d.onSelectTemplate}:{})}));else if(d.action==='loading'){setReady(false);setDoc(x=>({...x,error:null}))}else if(d.action==='ready'){setReady(false);setDoc(x=>({...x,html:d.html,paper:d.paper,error:null}))}}};window.addEventListener('workspace-document-preview',listener);return()=>window.removeEventListener('workspace-document-preview',listener)},[]);
 useEffect(()=>{if(!doc)return;const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';root.current?.querySelector('button')?.focus();const key=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=[...root.current.querySelectorAll('button:not(:disabled),select:not(:disabled),iframe')];if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0]?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);if(previous?.isConnected)previous.focus()}},[Boolean(doc)]);
 useEffect(()=>{if(!doc||!area.current)return;const ro=new ResizeObserver(entries=>setViewport(entries[0].contentRect.width));ro.observe(area.current);return()=>ro.disconnect()},[Boolean(doc),full]);
 async function loaded(){const node=frame.current,id=doc.id;try{await Promise.race([new Promise(r=>setTimeout(r,5000)),Promise.all([node.contentDocument.fonts?.ready,...[...node.contentDocument.images].map(i=>i.complete?Promise.resolve():new Promise(r=>{i.onload=r;i.onerror=r}))])]);if(current.current!==id||frame.current!==node)return;setHeight(Math.max(node.contentDocument.documentElement.scrollHeight,doc.paper==='A5'?794:doc.paper?.endsWith('mm')?350:1123));setReady(true)}catch{if(current.current===id)setReady(true)}}
 if(!doc)return null;const width=doc.paper==='A5'?560:doc.paper==='80mm'?302:doc.paper==='58mm'?219:794,zoom=fit?Math.min(1,(viewport-40)/width):scale;
 return <div className="pdf-preview-overlay"><section ref={root} className={`pdf-preview-modal ${full?'is-fullscreen':''}`} role="dialog" aria-modal="true" aria-label="PDF preview"><header><div><strong>{doc.title}</strong><small>Print or save as PDF</small></div><nav>{doc.templates&&<label className="pdf-template-select"><span>Template</span><select aria-label="Print template" value={doc.selectedTemplate||'initial'} onChange={e=>{const value=e.target.value;setDoc(x=>({...x,selectedTemplate:value}));doc.onSelectTemplate?.(value)}}><option value="initial">Document layout</option><option value="">Default {doc.title?.includes('Receipt')?'receipt':'layout'}</option>{doc.templates.map(t=><option key={t.id} value={t.id}>{t.name} · {t.kind}</option>)}</select></label>}<button title="Zoom out" aria-label="Zoom out" disabled={!ready} onClick={()=>{setFit(false);setScale(Math.max(.25,zoom-.15))}}>−</button><button title="Fit page" aria-label="Fit page" onClick={()=>setFit(true)}>{Math.round(zoom*100)}%</button><button title="Zoom in" aria-label="Zoom in" disabled={!ready} onClick={()=>{setFit(false);setScale(Math.min(2,zoom+.15))}}>＋</button><button title={full?'Exit full screen':'Full screen'} aria-label={full?'Exit full screen':'Full screen'} onClick={()=>setFull(x=>!x)}>⛶</button><button title="Print / Save PDF" aria-label="Print / Save PDF" className="primary" disabled={!ready} onClick={()=>{frame.current.contentWindow.focus();frame.current.contentWindow.print()}}>Print / Save PDF</button><button title="Close preview" aria-label="Close preview" onClick={close}>×</button></nav></header><div ref={area} className="pdf-preview-area">{doc.error?<div className="pdf-preview-error" role="alert"><strong>Preview could not be prepared</strong><p>{doc.error}</p><button onClick={close}>Close</button></div>:<>{!ready&&<div className="pdf-preview-loading" role="status"><span className="pdf-spinner"/><strong>Preparing your document</strong><small>Loading the layout and artwork…</small><div className="pdf-loading-paper"><i/><i/><i/><i/></div></div>}{doc.html&&<div className="pdf-preview-sheet" style={{width:width*zoom,height:height*zoom,visibility:ready?'visible':'hidden'}}><iframe ref={frame} title="PDF document preview" sandbox="allow-same-origin allow-modals" srcDoc={doc.html} onLoad={loaded} style={{width,height,transform:`scale(${zoom})`}}/></div>}</>}</div></section></div>
}
