'use client';
import dynamic from 'next/dynamic';
const BillingSettings=dynamic(()=>import('./BillingSettings'),{loading:()=> <div className="business-empty">Loading billing preferences…</div>});
const PrintSettings=dynamic(()=>import('./PrintSettings'),{loading:()=> <div className="business-empty">Loading print settings…</div>});
import AccessManagement from './AccessManagement';
import CommunicationsSettings from './CommunicationsSettings';
import ResalePlan from './ResalePlan';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import {userError} from '../lib/userError';

const DEFAULT_MODULES=['dashboard','cases','documents','operations','deliveries','custody','appointments','batches','courier','payments','reports','import','crm','sales','services'];
const MODULE_LABELS={dashboard:'Dashboard',cases:'Cases',documents:'Documents & Stages',operations:'Operations',deliveries:'Deliveries',custody:'Custody',appointments:'Appointments',batches:'Batch Reports',courier:'Courier Shipments',payments:'Payments',reports:'Reports',import:'Excel Import',crm:'CRM',sales:'Sales',services:'Services'};
const emptyOrganization={name:'',slug:'',legal_name:'',deployment_mode:'Tenant',contact_email:'',contact_phone:'',timezone:'Asia/Qatar',currency_code:'QAR'};
const emptySettings={product_name:'Document Tracker',company_name:'',short_name:'',logo_url:'',favicon_url:'',app_icon_url:'',primary_domain:'',primary_color:'#3265DF',secondary_color:'#17879A',accent_color:'#15A37D',surface_color:'#F4F7FC',login_title:'Document operations, organized.',login_subtitle:'Secure case, payment, delivery and custody management.',login_background_url:'',login_kicker:'LIVE OPERATIONS WORKSPACE',login_welcome_title:'Welcome back',login_welcome_subtitle:'Sign in to continue to your operations dashboard.',login_button_text:'Sign in to workspace',sidebar_logo_visible:true,sidebar_logo_size:100,sidebar_logo_alignment:'center',sidebar_logo_background:'#FFFFFF',sidebar_logo_radius:14,sidebar_logo_container_width:190,sidebar_logo_container_height:64,login_logo_visible:true,login_logo_size:100,login_logo_alignment:'left',login_logo_background:'#FFFFFF',login_logo_radius:14,login_logo_container_width:220,login_logo_container_height:72,login_card_logo_visible:true,login_card_logo_size:100,login_card_logo_alignment:'left',login_card_logo_background:'#FFFFFF',login_card_logo_radius:14,login_card_logo_container_width:220,login_card_logo_container_height:64,tracking_base_url:'',support_email:'',support_phone:'',website_url:'',address:'',footer_text:'',label_width_mm:75,label_height_mm:35,enabled_modules:DEFAULT_MODULES,whatsapp_automation_enabled:false};
const ASSETS=[
  {kind:'logo',field:'logo_url',label:'Company logo',hint:'PNG, JPG or WebP · transparent background recommended'},
  {kind:'favicon',field:'favicon_url',label:'Browser favicon',hint:'Square PNG · 64×64 recommended'},
  {kind:'app_icon',field:'app_icon_url',label:'Mobile app icon',hint:'Square PNG · 1024×1024 recommended'},
  {kind:'login_background',field:'login_background_url',label:'Login background',hint:'Wide JPG, PNG or WebP · 1600×1200 recommended'}
];

function AssetUploader({asset,value,busy,onUpload,onClear}){
  return <div className="branding-asset-card">
    <div className={`branding-asset-thumb ${asset.kind}`}>{value?<img src={value} alt=""/>:<span>＋</span>}</div>
    <div><strong>{asset.label}</strong><small>{asset.hint}</small><div className="branding-asset-actions"><label className="secondary">{busy?'Uploading…':'Upload image'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)onUpload(asset,file);e.target.value=''}}/></label>{value&&<button type="button" className="text-danger" onClick={()=>onClear(asset.field)}>Remove</button>}</div></div>
  </div>
}

function LogoLayoutStudio({settings,setField}){
  const logo=settings.logo_url;
  const mark=(settings.short_name||settings.company_name||'D').slice(0,1).toUpperCase();
  const controls=[
    {title:'Application sidebar',description:'Logo shown at the top of the application menu.',prefix:'sidebar_logo',surface:'sidebar',defaultAlign:'center',defaultWidth:190,defaultHeight:64,maxWidth:240},
    {title:'Login story panel',description:'Logo on the large desktop marketing panel.',prefix:'login_logo',surface:'login',defaultAlign:'left',defaultWidth:220,defaultHeight:72,maxWidth:360},
    {title:'Login sign-in card',description:'Independent logo above the login form on desktop and mobile.',prefix:'login_card_logo',surface:'login-card',defaultAlign:'left',defaultWidth:220,defaultHeight:64,maxWidth:360}
  ];
  return <div className="logo-layout-studio">{controls.map(item=>{const size=Number(settings[`${item.prefix}_size`]||100),alignment=settings[`${item.prefix}_alignment`]||item.defaultAlign,visible=settings[`${item.prefix}_visible`]!==false,background=settings[`${item.prefix}_background`]||'#FFFFFF',radius=Number(settings[`${item.prefix}_radius`]??14),width=Number(settings[`${item.prefix}_container_width`]||item.defaultWidth),height=Number(settings[`${item.prefix}_container_height`]||item.defaultHeight);return <section className="logo-layout-control" key={item.surface}>
    <div className={`logo-layout-preview ${item.surface}`}><div className="logo-layout-preview-label">{item.title} preview</div><div className="logo-layout-preview-stage" style={{justifyContent:alignment}}><div className={`logo-layout-preview-box ${!visible?'logo-is-hidden':''}`} style={{justifyContent:alignment,background,borderRadius:`${radius}px`,width:`min(100%,${width}px)`,height:`${height}px`,'--layout-logo-scale':size/100,'--layout-logo-origin':alignment==='left'?'left center':alignment==='right'?'right center':'center'}}>{visible?(logo?<img src={logo} alt="Company logo"/>:<b>{mark}</b>):<span className="logo-hidden-state">Hidden</span>}</div></div></div>
    <div className="logo-layout-fields"><div className="logo-layout-heading"><div><strong>{item.title}</strong><span>{item.description}</span></div><label className="logo-visibility"><input type="checkbox" checked={visible} onChange={e=>setField(`${item.prefix}_visible`,e.target.checked)}/><i></i><b>{visible?'Shown':'Hidden'}</b></label></div><label>Logo scale <b>{size}%</b><input type="range" min="50" max="130" step="5" value={size} disabled={!visible} onChange={e=>setField(`${item.prefix}_size`,Number(e.target.value))}/></label><label>Container radius <b>{radius}px</b><input type="range" min="0" max="32" step="1" value={radius} onChange={e=>setField(`${item.prefix}_radius`,Number(e.target.value))}/></label><label>Container width <b>{width}px</b><input type="range" min="80" max={item.maxWidth} step="5" value={width} onChange={e=>setField(`${item.prefix}_container_width`,Number(e.target.value))}/></label><label>Container height <b>{height}px</b><input type="range" min="44" max="120" step="2" value={height} onChange={e=>setField(`${item.prefix}_container_height`,Number(e.target.value))}/></label><label>Alignment<select value={alignment} disabled={!visible} onChange={e=>setField(`${item.prefix}_alignment`,e.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label><label>Container color<div className="logo-color-field"><input type="color" value={background} onChange={e=>setField(`${item.prefix}_background`,e.target.value.toUpperCase())}/><input value={background} maxLength="7" onChange={e=>setField(`${item.prefix}_background`,e.target.value)} onBlur={e=>{if(!/^#[0-9a-f]{6}$/i.test(e.target.value))setField(`${item.prefix}_background`,'#FFFFFF')}}/></div></label></div>
  </section>})}</div>
}

function LoginPreview({settings,organization,mobile}){
  const company=settings.company_name||organization?.name||'Your Organization';
  const product=settings.product_name||'Document Tracker';
  const mark=(settings.short_name||company||'D').slice(0,1).toUpperCase();
  const hasLogo=Boolean(settings.logo_url),showLogo=hasLogo&&settings.login_logo_visible!==false,showCardLogo=hasLogo&&settings.login_card_logo_visible!==false;
  const loginLogoStyle={justifyContent:settings.login_logo_alignment||'left','--preview-logo-size':`${Number(settings.login_logo_size||100)}%`,background:settings.login_logo_background||'#FFFFFF',borderRadius:`${Number(settings.login_logo_radius??14)}px`,width:`min(100%,${Number(settings.login_logo_container_width||220)}px)`,height:`${Number(settings.login_logo_container_height||72)}px`};
  const cardLogoStyle={justifyContent:settings.login_card_logo_alignment||'left','--preview-logo-size':`${Number(settings.login_card_logo_size||100)}%`,background:settings.login_card_logo_background||'#FFFFFF',borderRadius:`${Number(settings.login_card_logo_radius??14)}px`,width:`min(100%,${Number(settings.login_card_logo_container_width||220)}px)`,height:`${Number(settings.login_card_logo_container_height||64)}px`,marginLeft:settings.login_card_logo_alignment==='right'?'auto':settings.login_card_logo_alignment==='center'?'auto':0,marginRight:settings.login_card_logo_alignment==='left'?0:'auto'};
  const panelStyle={'--preview-primary':settings.primary_color||'#3265DF','--preview-secondary':settings.secondary_color||'#17879A',backgroundImage:settings.login_background_url?`linear-gradient(135deg,rgba(7,23,45,.94),rgba(12,44,86,.82)),url("${settings.login_background_url}")`:undefined};
  return <div className={`login-brand-preview ${mobile?'mobile':''}`}><div className="login-preview-screen">
    <section className="login-preview-visual" style={panelStyle}>{(!hasLogo||showLogo)&&<div className={`login-preview-brand ${showLogo?'has-logo':''}`}>{showLogo?<div className="login-preview-logo-container" style={loginLogoStyle}><img src={settings.logo_url} alt="Company logo"/></div>:<><div>{mark}</div><span><b>{product}</b><small>{company}</small></span></>}</div>}<div className="login-preview-copy"><small>{settings.login_kicker||'LIVE OPERATIONS WORKSPACE'}</small><h4>{settings.login_title||'Document operations, organized.'}</h4><p>{settings.login_subtitle||'Secure case, payment, delivery and custody management.'}</p></div><div className="login-preview-stats"><span><b>1,636</b> Active cases</span><span><b>650</b> Ready</span><span><b>12</b> In transit</span></div></section>
    <section className="login-preview-form" style={{'--preview-primary':settings.primary_color||'#3265DF','--preview-surface':settings.surface_color||'#F4F7FC'}}>{(!hasLogo||showCardLogo)&&<div className={`login-preview-mobile-brand ${showCardLogo?'has-logo':''}`}>{showCardLogo?<div className="login-preview-logo-container" style={cardLogoStyle}><img src={settings.logo_url} alt="Company logo"/></div>:<><b>{mark}</b><span>{product}<small>{company}</small></span></>}</div>}<i>● Secure operations workspace</i><h4>{settings.login_welcome_title||'Welcome back'}</h4><p>{settings.login_welcome_subtitle||'Sign in to continue to your operations dashboard.'}</p><label>Email address<span>name@company.com</span></label><label>Password<span>••••••••••</span></label><button type="button">{settings.login_button_text||'Sign in to workspace'} →</button><small>{settings.footer_text||`${company} · Operations Command Center`}</small></section>
  </div></div>
}

export default function ProductSettings({session,profile,currentOrganization,onBrandChange,notify,initialTab}){
  const platform=Boolean(profile?.is_platform_super_admin);
  const [settingsSearch,setSettingsSearch]=useState('');
  const settingsNames={branding:'Company & branding',billing:'Numbering & billing',print:'Print templates',branches:'Branches',staff:'Users & roles',modules:'Module access',communications:'Communications',plan:'Subscription',companies:'Companies'};
  const [tab,setTab]=useState(()=>{if(initialTab)return initialTab;try{return sessionStorage.getItem('workspace-settings-tab')||'branding'}catch{return 'branding'}}),[organizations,setOrganizations]=useState([]),[organizationId,setOrganizationId]=useState(profile?.organization_id||''),[settings,setSettings]=useState(emptySettings),[branches,setBranches]=useState([]),[staff,setStaff]=useState([]),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(''),[previewMobile,setPreviewMobile]=useState(false),[newOrg,setNewOrg]=useState(emptyOrganization),[newBranch,setNewBranch]=useState(''),[invite,setInvite]=useState({email:'',full_name:'',role:'staff',branch_id:'',password:'',staff_modules:null});
  const selectedOrganization=useMemo(()=>organizations.find(x=>x.id===organizationId)||currentOrganization,[organizations,organizationId,currentOrganization]);
  const setField=(field,value)=>setSettings(s=>({...s,[field]:value}));

  useEffect(()=>{if(initialTab)setTab(initialTab)},[initialTab]);
  useEffect(()=>{loadOrganizations()},[]);
  useEffect(()=>{if(organizationId){try{localStorage.setItem('platform_selected_organization',organizationId)}catch{}loadWorkspace(organizationId)}},[organizationId]);
  async function loadOrganizations(){const {data,error}=await supabase.from('organizations').select('*').order('name');if(error)return notify(userError(error));const rows=data||[];let remembered='';try{remembered=localStorage.getItem('platform_selected_organization')||''}catch{}setOrganizations(rows);setOrganizationId(prev=>prev||profile?.organization_id||(rows.some(x=>x.id===remembered)?remembered:'')||rows[0]?.id||'');if(platform&&!rows.length)setTab('companies')}
  async function loadAccounts(orgId){
    const {data:{session:authSession}}=await supabase.auth.getSession();
    const response=await fetch(`/api/platform/users?organization_id=${encodeURIComponent(orgId)}`,{headers:{authorization:`Bearer ${authSession?.access_token||''}`},cache:'no-store'});
    const out=await response.json();if(!response.ok)throw new Error(out.error||'Accounts could not be loaded.');return out.accounts||[];
  }
  async function loadWorkspace(orgId){
    setBusy(true);
    try{
      const [s,b,people]=await Promise.all([supabase.from('organization_settings').select('*').eq('organization_id',orgId).maybeSingle(),supabase.from('branches').select('id,name,is_active,organization_id').eq('organization_id',orgId).order('name'),loadAccounts(orgId)]);
      if(s.error||b.error)throw s.error||b.error;
      const next={...emptySettings,...(s.data||{}),organization_id:orgId,enabled_modules:Array.isArray(s.data?.enabled_modules)?s.data.enabled_modules:DEFAULT_MODULES};
      setSettings(next);setBranches(b.data||[]);setStaff(people);onBrandChange?.(next);
    }catch(error){notify(userError(error))}finally{setBusy(false)}
  }
  async function saveBrand(e){e.preventDefault();if(!organizationId)return notify('Select a company first.');setBusy(true);const payload={...settings,organization_id:organizationId,company_name:String(settings.company_name||selectedOrganization?.name||'').trim(),product_name:String(settings.product_name||'Document Tracker').trim(),updated_at:new Date().toISOString(),updated_by:session.user.id,whatsapp_automation_enabled:false};const {data,error}=await supabase.from('organization_settings').upsert(payload,{onConflict:'organization_id'}).select('*').single();setBusy(false);if(error)return notify(userError(error));setSettings({...emptySettings,...data});onBrandChange?.(data);notify('Branding saved permanently. Login and application previews are now updated.')}
  async function uploadAsset(asset,file){if(!organizationId)return notify('Select a company first.');setUploading(asset.kind);const {data:{session:authSession}}=await supabase.auth.getSession();const form=new FormData();form.append('organization_id',organizationId);form.append('kind',asset.kind);form.append('file',file);const response=await fetch('/api/platform/branding-upload',{method:'POST',headers:{authorization:`Bearer ${authSession?.access_token||''}`},body:form});const out=await response.json().catch(()=>({}));setUploading('');if(!response.ok)return notify(out.error||'Unable to upload image.');const next={...emptySettings,...(out.settings||settings),[asset.field]:out.url};setSettings(next);onBrandChange?.(next);notify(`${asset.label} uploaded and saved.`)}
  function clearAsset(field){setField(field,'')}
  async function createOrganization(e){e.preventDefault();if(!platform)return;setBusy(true);const payload={...newOrg,name:newOrg.name.trim(),slug:newOrg.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),created_by:session.user.id};const {data,error}=await supabase.from('organizations').insert(payload).select('*').single();if(!error&&data){await supabase.from('organization_settings').insert({organization_id:data.id,company_name:data.name,product_name:'Document Tracker'});setNewOrg(emptyOrganization);await loadOrganizations();setOrganizationId(data.id);notify(`${data.name} created.`)}else notify(error?userError(error):'Unable to create company.');setBusy(false)}
  async function updateOrganization(patch){if(!platform)return;const {error}=await supabase.from('organizations').update(patch).eq('id',organizationId);if(error)return notify(userError(error));await loadOrganizations();notify('Company record updated.')}
  async function addBranch(e){e.preventDefault();const name=newBranch.trim();if(!name)return;setBusy(true);const {error}=await supabase.from('branches').insert({name,organization_id:organizationId,is_active:true});setBusy(false);if(error)return notify(userError(error));setNewBranch('');await loadWorkspace(organizationId);notify(`${name} added.`)}
  async function toggleBranch(branch){const {error}=await supabase.from('branches').update({is_active:!branch.is_active}).eq('id',branch.id);if(error)return notify(userError(error));await loadWorkspace(organizationId)}
  async function accountRequest(method,body){
    setBusy(true);
    try{
      const {data:{session:authSession}}=await supabase.auth.getSession();
      const response=await fetch('/api/platform/users',{method,headers:{'content-type':'application/json',authorization:`Bearer ${authSession?.access_token||''}`},body:JSON.stringify(body)});
      const out=await response.json().catch(()=>({}));
      if(!response.ok){notify(out.error||'The account could not be saved.');return false}
      await loadWorkspace(organizationId);notify(out.message||'Account saved.');return true;
    }catch{notify('The connection could not be completed. Please retry.');return false}finally{setBusy(false)}
  }
  async function patchStaff(id,patch){return accountRequest('PATCH',{id,...patch})}
  async function deleteStaff(id){return accountRequest('DELETE',{id})}
  async function createStaff(e){e.preventDefault();const ok=await accountRequest('POST',{...invite,organization_id:organizationId});if(ok)setInvite({email:'',full_name:'',role:'staff',branch_id:'',password:'',staff_modules:null});return ok}
  const toggleModule=key=>setSettings(s=>({...s,enabled_modules:s.enabled_modules.includes(key)?s.enabled_modules.filter(x=>x!==key):[...s.enabled_modules,key]}));

  return <section className="product-settings">
    <div className="product-settings-hero"><div><span>WHITE-LABEL CONTROL CENTER</span><h2>{platform?'Platform administration':'Company administration'}</h2><p>Manage company identity, login experience, branches, staff and the features available across web and mobile.</p></div>{platform&&<select value={organizationId} onChange={e=>setOrganizationId(e.target.value)}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name} · {o.status}</option>)}</select>}</div>
    <div className="settings-search-bar"><span aria-hidden="true">⌕</span><input aria-label="Search settings groups" placeholder="Search settings…" value={settingsSearch} onChange={e=>setSettingsSearch(e.target.value)}/>{settingsSearch&&<button type="button" title="Clear search" aria-label="Clear settings search" onClick={()=>setSettingsSearch('')}>×</button>}</div><div className="product-settings-tabs">{['branding','billing','print','branches','staff','modules','communications','plan',...(platform?['companies']:[])].filter(x=>settingsNames[x].toLowerCase().includes(settingsSearch.toLowerCase())).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{settingsNames[x]}</button>)}</div>
    {busy&&<div className="settings-loading">Saving or loading company settings…</div>}
    {tab==='billing'&&organizationId&&<BillingSettings key={organizationId} orgId={organizationId} notify={notify}/>}
    {tab==='print'&&organizationId&&<PrintSettings key={organizationId} orgId={organizationId} brand={settings} organization={selectedOrganization} notify={notify}/>}
    {tab==='branding'&&!organizationId&&<div className="settings-card settings-empty-state"><span>NO COMPANY SELECTED</span><h3>Create a client company first</h3><p>The platform owner remains global. Branding, branches and client access are configured separately inside each company.</p>{platform&&<button type="button" className="primary" onClick={()=>setTab('companies')}>Create Company</button>}</div>}
    {tab==='branding'&&organizationId&&<form className="settings-card branding-studio" onSubmit={saveBrand}>
      <div className="settings-section-head"><div><span>LIVE BRAND STUDIO</span><h3>Branding and login experience</h3><p>Every change appears in the preview. Save Branding publishes text, colors and links permanently.</p></div><div className="preview-device-switch"><button type="button" className={!previewMobile?'active':''} onClick={()=>setPreviewMobile(false)}>Desktop</button><button type="button" className={previewMobile?'active':''} onClick={()=>setPreviewMobile(true)}>Mobile</button></div></div>
      <LoginPreview settings={settings} organization={selectedOrganization} mobile={previewMobile}/>
      <div className="branding-editor-grid">
        <details className="branding-editor-section branding-collapsible"><summary><EditorTitle number="01" title="Brand assets and logo layout" text="Upload assets and independently control the sidebar, login story and sign-in card logos."/><span className="branding-collapse-chip">Open editor</span></summary><div className="branding-collapsible-body"><div className="branding-assets-grid">{ASSETS.map(asset=><AssetUploader key={asset.kind} asset={asset} value={settings[asset.field]} busy={uploading===asset.kind} onUpload={uploadAsset} onClear={clearAsset}/>)}</div><LogoLayoutStudio settings={settings} setField={setField}/></div></details>
        <section className="branding-editor-section"><EditorTitle number="02" title="Identity and colors" text="Used across the login screen, navigation, exports and receipts."/><div className="settings-brand-grid compact"><label>Product name<input value={settings.product_name||''} onChange={e=>setField('product_name',e.target.value)}/></label><label>Company name<input required value={settings.company_name||''} onChange={e=>setField('company_name',e.target.value)}/></label><label>Short name<input value={settings.short_name||''} onChange={e=>setField('short_name',e.target.value)}/></label><label>Primary login domain<input value={settings.primary_domain||''} onChange={e=>setField('primary_domain',e.target.value.replace(/^https?:\/\//,'').split('/')[0])} placeholder="tracker.customer.com"/></label><ColorFields settings={settings} setField={setField}/></div></section>
        <section className="branding-editor-section"><EditorTitle number="03" title="Login page content" text="Customize both the visual story panel and the sign-in card."/><div className="settings-brand-grid compact"><label>Login eyebrow<input value={settings.login_kicker||''} onChange={e=>setField('login_kicker',e.target.value)}/></label><label>Sign-in button text<input value={settings.login_button_text||''} onChange={e=>setField('login_button_text',e.target.value)}/></label><label className="wide">Main login heading<input value={settings.login_title||''} onChange={e=>setField('login_title',e.target.value)}/></label><label className="wide">Main login description<textarea rows="2" value={settings.login_subtitle||''} onChange={e=>setField('login_subtitle',e.target.value)}/></label><label>Sign-in card heading<input value={settings.login_welcome_title||''} onChange={e=>setField('login_welcome_title',e.target.value)}/></label><label>Sign-in card description<input value={settings.login_welcome_subtitle||''} onChange={e=>setField('login_welcome_subtitle',e.target.value)}/></label></div></section>
        <section className="branding-editor-section"><EditorTitle number="04" title="Contact and customer experience" text="Used in public tracking, exports, receipts and support areas."/><div className="settings-brand-grid compact"><label>Tracking URL<input type="url" value={settings.tracking_base_url||''} placeholder="https://yourwebsite.com/track/" onChange={e=>setField('tracking_base_url',e.target.value)}/><small>Clean links use /track/reference with Connector 2.6.2. Add ?ref= to keep query links.</small></label><label>Website<input type="url" value={settings.website_url||''} onChange={e=>setField('website_url',e.target.value)}/></label><label>Support email<input type="email" value={settings.support_email||''} onChange={e=>setField('support_email',e.target.value)}/></label><label>Support mobile<input value={settings.support_phone||''} onChange={e=>setField('support_phone',e.target.value)}/></label><label className="wide">Address<textarea rows="2" value={settings.address||''} onChange={e=>setField('address',e.target.value)}/></label><label className="wide">Export, receipt and login footer<input value={settings.footer_text||''} onChange={e=>setField('footer_text',e.target.value)}/></label></div></section>
      </div><div className="branding-save-bar"><div><strong>Ready to publish?</strong><span>Uploads are already saved. Save to publish all text, colors and links.</span></div><button className="primary" disabled={busy||Boolean(uploading)}>{busy?'Saving…':'Save Branding Permanently'}</button></div>
    </form>}
    {tab==='branches'&&<BranchesCard branches={branches} newBranch={newBranch} setNewBranch={setNewBranch} addBranch={addBranch} toggleBranch={toggleBranch}/>} 
    {tab==='staff'&&<AccessManagement actorId={profile?.id} invite={invite} setInvite={setInvite} branches={branches} staff={staff} busy={busy} createStaff={createStaff} patchStaff={patchStaff} platform={platform} companyModules={settings.enabled_modules} moduleLabels={MODULE_LABELS} deleteStaff={deleteStaff} portal={settings.primary_domain}/>}
    {tab==='modules'&&<form className="settings-card" onSubmit={saveBrand}><div className="settings-section-head"><div><span>PRODUCT CONFIGURATION</span><h3>Enabled modules</h3><p>Web and mobile read the same list. Core security remains active when a module is hidden.</p></div></div><div className="module-settings-grid">{Object.entries(MODULE_LABELS).map(([key,label])=><label key={key} className={settings.enabled_modules.includes(key)?'active':''}><input type="checkbox" checked={settings.enabled_modules.includes(key)} onChange={()=>toggleModule(key)}/><span>{label}</span></label>)}</div><div className="settings-hold"><strong>Customer updates</strong><span>Configure email and official WhatsApp senders in Communications. Automation remains off until activated.</span></div><div className="settings-save"><button className="primary">Save Module Settings</button></div></form>}
    {tab==='communications'&&<CommunicationsSettings organizationId={organizationId} notify={notify} companyName={selectedOrganization?.name}/>}
    {tab==='plan'&&<ResalePlan organizationId={organizationId} platform={platform} moduleLabels={MODULE_LABELS} notify={notify}/>}
    {tab==='companies'&&platform&&<CompaniesCard organizations={organizations} organizationId={organizationId} setOrganizationId={setOrganizationId} selectedOrganization={selectedOrganization} newOrg={newOrg} setNewOrg={setNewOrg} createOrganization={createOrganization} updateOrganization={updateOrganization} notify={notify}/>} 
  </section>
}

function EditorTitle({number,title,text}){return <div className="branding-editor-title"><span>{number}</span><div><h4>{title}</h4><p>{text}</p></div></div>}
function ColorFields({settings,setField}){return <div className="settings-color-row">{[['Primary','primary_color'],['Secondary','secondary_color'],['Accent','accent_color'],['Surface','surface_color']].map(([label,key])=><label key={key}>{label}<input type="color" value={settings[key]} onChange={e=>setField(key,e.target.value)}/><code>{settings[key]}</code></label>)}</div>}
function BranchesCard({branches,newBranch,setNewBranch,addBranch,toggleBranch}){return <div className="settings-card"><div className="settings-section-head"><div><span>OPERATING LOCATIONS</span><h3>Branches</h3></div></div><form className="settings-inline-create" onSubmit={addBranch}><input value={newBranch} onChange={e=>setNewBranch(e.target.value)} placeholder="New branch name"/><button className="primary">Add Branch</button></form><div className="settings-list">{branches.map(b=><div key={b.id}><span><b>{b.name}</b><small>{b.is_active?'Available throughout the product':'Hidden from new activity'}</small></span><button className="secondary" onClick={()=>toggleBranch(b)}>{b.is_active?'Deactivate':'Activate'}</button></div>)}</div></div>}
function CompaniesCard({organizations,organizationId,setOrganizationId,selectedOrganization,newOrg,setNewOrg,createOrganization,updateOrganization,notify}){const copySlug=async()=>{try{await navigator.clipboard.writeText(selectedOrganization.slug);notify?.(`Organization slug “${selectedOrganization.slug}” copied.`)}catch{notify?.('Unable to copy the organization slug.')}};return <div className="settings-card"><div className="settings-section-head"><div><span>PLATFORM SUPER ADMIN ONLY</span><h3>Companies and installations</h3><p>The organization slug is required by WordPress connectors and public tracking links.</p></div></div><form className="company-create-grid" onSubmit={createOrganization}><input required value={newOrg.name} onChange={e=>setNewOrg({...newOrg,name:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-')})} placeholder="Company name"/><input required value={newOrg.slug} onChange={e=>setNewOrg({...newOrg,slug:e.target.value})} placeholder="company-slug"/><input value={newOrg.legal_name} onChange={e=>setNewOrg({...newOrg,legal_name:e.target.value})} placeholder="Legal name"/><select value={newOrg.deployment_mode} onChange={e=>setNewOrg({...newOrg,deployment_mode:e.target.value})}><option value="Tenant">Shared SaaS tenant</option><option value="Dedicated">Dedicated installation</option></select><input type="email" value={newOrg.contact_email} onChange={e=>setNewOrg({...newOrg,contact_email:e.target.value})} placeholder="Contact email"/><button className="primary">Create Company</button></form><div className="settings-company-grid">{organizations.map(o=><button type="button" key={o.id} className={o.id===organizationId?'active':''} onClick={()=>setOrganizationId(o.id)}><strong>{o.name}</strong><span>{o.deployment_mode} · {o.status}</span><code>{o.slug}</code></button>)}</div>{selectedOrganization&&<><div className="company-slug-panel"><div><small>ORGANIZATION SLUG</small><strong>{selectedOrganization.slug}</strong><span>Use this exact value in the WordPress tracking connector.</span></div><button type="button" className="secondary" onClick={copySlug}>Copy Slug</button></div><div className="company-status-actions"><span>Selected: <b>{selectedOrganization.name}</b></span>{['Active','Suspended','Archived'].map(x=><button type="button" className={selectedOrganization.status===x?'primary':'secondary'} key={x} onClick={()=>updateOrganization({status:x})}>{x}</button>)}</div></>}</div>}
