'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';

const DEFAULT_MODULES=['dashboard','cases','documents','operations','deliveries','custody','appointments','batches','courier','payments','reports','import'];
const MODULE_LABELS={dashboard:'Dashboard',cases:'Cases',documents:'Documents & Stages',operations:'Operations',deliveries:'Deliveries',custody:'Custody',appointments:'Appointments',batches:'Batch Reports',courier:'Courier Shipments',payments:'Payments',reports:'Reports',import:'Excel Import'};
const emptyOrganization={name:'',slug:'',legal_name:'',deployment_mode:'Tenant',contact_email:'',contact_phone:'',timezone:'Asia/Qatar',currency_code:'QAR'};
const emptySettings={product_name:'Document Tracker',company_name:'',short_name:'',logo_url:'',favicon_url:'',app_icon_url:'',primary_domain:'',primary_color:'#3265DF',secondary_color:'#17879A',accent_color:'#15A37D',surface_color:'#F4F7FC',login_title:'Document operations, organized.',login_subtitle:'Secure case, payment, delivery and custody management.',tracking_base_url:'',support_email:'',support_phone:'',website_url:'',address:'',footer_text:'',label_width_mm:75,label_height_mm:35,enabled_modules:DEFAULT_MODULES,whatsapp_automation_enabled:false};

export default function ProductSettings({session,profile,currentOrganization,onBrandChange,notify}){
  const platform=Boolean(profile?.is_platform_super_admin);
  const [tab,setTab]=useState('branding'),[organizations,setOrganizations]=useState([]),[organizationId,setOrganizationId]=useState(profile?.organization_id||''),[settings,setSettings]=useState(emptySettings),[branches,setBranches]=useState([]),[staff,setStaff]=useState([]),[busy,setBusy]=useState(false),[newOrg,setNewOrg]=useState(emptyOrganization),[newBranch,setNewBranch]=useState(''),[invite,setInvite]=useState({email:'',full_name:'',role:'staff',branch_id:'',password:''});
  const selectedOrganization=useMemo(()=>organizations.find(x=>x.id===organizationId)||currentOrganization,[organizations,organizationId,currentOrganization]);

  useEffect(()=>{loadOrganizations()},[]);
  useEffect(()=>{if(organizationId)loadWorkspace(organizationId)},[organizationId]);
  async function loadOrganizations(){
    const {data,error}=await supabase.from('organizations').select('*').order('name');
    if(error)return notify(error.message);
    setOrganizations(data||[]);setOrganizationId(prev=>prev||profile?.organization_id||data?.[0]?.id||'');
  }
  async function loadWorkspace(orgId){
    setBusy(true);
    const [s,b,p]=await Promise.all([
      supabase.from('organization_settings').select('*').eq('organization_id',orgId).maybeSingle(),
      supabase.from('branches').select('id,name,is_active,organization_id').eq('organization_id',orgId).order('name'),
      supabase.from('profiles').select('id,full_name,role,branch_id,is_active,organization_id,is_platform_super_admin').eq('organization_id',orgId).order('full_name')
    ]);
    if(s.error||b.error||p.error)notify(s.error?.message||b.error?.message||p.error?.message);
    setSettings({...emptySettings,...(s.data||{}),organization_id:orgId,enabled_modules:Array.isArray(s.data?.enabled_modules)?s.data.enabled_modules:DEFAULT_MODULES});setBranches(b.data||[]);setStaff(p.data||[]);setBusy(false);
  }
  async function saveBrand(e){
    e.preventDefault();setBusy(true);
    const payload={...settings,organization_id:organizationId,company_name:String(settings.company_name||selectedOrganization?.name||'').trim(),product_name:String(settings.product_name||'Document Tracker').trim(),updated_at:new Date().toISOString(),updated_by:session.user.id,whatsapp_automation_enabled:false};
    const {data,error}=await supabase.from('organization_settings').upsert(payload,{onConflict:'organization_id'}).select('*').single();
    setBusy(false);if(error)return notify(error.message);setSettings(data);onBrandChange?.(data);notify('Company branding and product settings saved.');
  }
  async function createOrganization(e){
    e.preventDefault();if(!platform)return;setBusy(true);
    const payload={...newOrg,name:newOrg.name.trim(),slug:newOrg.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),created_by:session.user.id};
    const {data,error}=await supabase.from('organizations').insert(payload).select('*').single();
    if(!error&&data){await supabase.from('organization_settings').insert({organization_id:data.id,company_name:data.name,product_name:'Document Tracker'});setNewOrg(emptyOrganization);await loadOrganizations();setOrganizationId(data.id);notify(`${data.name} created.`)}else notify(error?.message||'Unable to create company.');setBusy(false);
  }
  async function updateOrganization(patch){
    if(!platform)return;const {error}=await supabase.from('organizations').update(patch).eq('id',organizationId);if(error)return notify(error.message);await loadOrganizations();notify('Company record updated.');
  }
  async function addBranch(e){e.preventDefault();const name=newBranch.trim();if(!name)return;setBusy(true);const {error}=await supabase.from('branches').insert({name,organization_id:organizationId,is_active:true});setBusy(false);if(error)return notify(error.message);setNewBranch('');await loadWorkspace(organizationId);notify(`${name} added.`)}
  async function toggleBranch(branch){const {error}=await supabase.from('branches').update({is_active:!branch.is_active}).eq('id',branch.id);if(error)return notify(error.message);await loadWorkspace(organizationId)}
  async function patchStaff(id,patch){const {error}=await supabase.from('profiles').update(patch).eq('id',id).eq('organization_id',organizationId);if(error)return notify(error.message);await loadWorkspace(organizationId);notify('Staff permissions updated.')}
  async function createStaff(e){
    e.preventDefault();setBusy(true);const {data:{session:authSession}}=await supabase.auth.getSession();
    const r=await fetch('/api/platform/users',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${authSession?.access_token||''}`},body:JSON.stringify({...invite,organization_id:organizationId})});const out=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return notify(out.error||'Unable to create staff account.');setInvite({email:'',full_name:'',role:'staff',branch_id:'',password:''});await loadWorkspace(organizationId);notify('Staff account created successfully.');
  }
  const toggleModule=key=>setSettings(s=>({...s,enabled_modules:s.enabled_modules.includes(key)?s.enabled_modules.filter(x=>x!==key):[...s.enabled_modules,key]}));
  return <section className="product-settings">
    <div className="product-settings-hero"><div><span>WHITE-LABEL CONTROL CENTER</span><h2>{platform?'Platform administration':'Company administration'}</h2><p>Manage company identity, branches, staff and the features available across web and mobile.</p></div>{platform&&<select value={organizationId} onChange={e=>setOrganizationId(e.target.value)}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name} · {o.status}</option>)}</select>}</div>
    <div className="product-settings-tabs">{['branding','branches','staff','modules',...(platform?['companies']:[])].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
    {busy&&<div className="settings-loading">Saving or loading company settings…</div>}
    {tab==='branding'&&<form className="settings-card settings-brand-grid" onSubmit={saveBrand}>
      <div className="settings-section-head"><div><span>COMPANY IDENTITY</span><h3>Branding and customer-facing details</h3></div><div className="brand-preview" style={{'--preview-a':settings.secondary_color,'--preview-b':settings.primary_color}}>{settings.logo_url?<img src={settings.logo_url} alt="Logo preview"/>:<b>{(settings.short_name||settings.company_name||'C').slice(0,1)}</b>}<span>{settings.product_name||'Document Tracker'}<small>{settings.company_name||selectedOrganization?.name}</small></span></div></div>
      <label>Product name<input value={settings.product_name||''} onChange={e=>setSettings({...settings,product_name:e.target.value})}/></label><label>Company name<input required value={settings.company_name||''} onChange={e=>setSettings({...settings,company_name:e.target.value})}/></label><label>Short name<input value={settings.short_name||''} onChange={e=>setSettings({...settings,short_name:e.target.value})}/></label><label>Logo URL<input type="url" value={settings.logo_url||''} onChange={e=>setSettings({...settings,logo_url:e.target.value})} placeholder="https://…/logo.png"/></label><label>Favicon URL<input type="url" value={settings.favicon_url||''} onChange={e=>setSettings({...settings,favicon_url:e.target.value})}/></label><label>Mobile app icon URL<input type="url" value={settings.app_icon_url||''} onChange={e=>setSettings({...settings,app_icon_url:e.target.value})}/></label>
      <div className="settings-color-row"><label>Primary<input type="color" value={settings.primary_color} onChange={e=>setSettings({...settings,primary_color:e.target.value})}/><code>{settings.primary_color}</code></label><label>Secondary<input type="color" value={settings.secondary_color} onChange={e=>setSettings({...settings,secondary_color:e.target.value})}/><code>{settings.secondary_color}</code></label><label>Accent<input type="color" value={settings.accent_color} onChange={e=>setSettings({...settings,accent_color:e.target.value})}/><code>{settings.accent_color}</code></label><label>Background<input type="color" value={settings.surface_color} onChange={e=>setSettings({...settings,surface_color:e.target.value})}/><code>{settings.surface_color}</code></label></div>
      <label className="wide">Login heading<input value={settings.login_title||''} onChange={e=>setSettings({...settings,login_title:e.target.value})}/></label><label className="wide">Login description<textarea rows="2" value={settings.login_subtitle||''} onChange={e=>setSettings({...settings,login_subtitle:e.target.value})}/></label><label>Primary login domain<input value={settings.primary_domain||''} onChange={e=>setSettings({...settings,primary_domain:e.target.value.replace(/^https?:\/\//,'').split('/')[0]})} placeholder="tracker.customer.com"/></label><label>Tracking URL<input type="url" value={settings.tracking_base_url||''} onChange={e=>setSettings({...settings,tracking_base_url:e.target.value})}/></label><label>Website<input type="url" value={settings.website_url||''} onChange={e=>setSettings({...settings,website_url:e.target.value})}/></label><label>Support email<input type="email" value={settings.support_email||''} onChange={e=>setSettings({...settings,support_email:e.target.value})}/></label><label>Support mobile<input value={settings.support_phone||''} onChange={e=>setSettings({...settings,support_phone:e.target.value})}/></label><label className="wide">Address<textarea rows="2" value={settings.address||''} onChange={e=>setSettings({...settings,address:e.target.value})}/></label><label className="wide">Export and receipt footer<input value={settings.footer_text||''} onChange={e=>setSettings({...settings,footer_text:e.target.value})}/></label><div className="settings-hold wide"><strong>Automatic WhatsApp</strong><span>On hold. Manual WhatsApp sharing remains available; no automatic messages will be sent.</span></div><div className="settings-save wide"><button className="primary" disabled={busy}>Save Company Settings</button></div>
    </form>}
    {tab==='branches'&&<div className="settings-card"><div className="settings-section-head"><div><span>OPERATING LOCATIONS</span><h3>Branches</h3></div></div><form className="settings-inline-create" onSubmit={addBranch}><input value={newBranch} onChange={e=>setNewBranch(e.target.value)} placeholder="New branch name"/><button className="primary">Add Branch</button></form><div className="settings-list">{branches.map(b=><div key={b.id}><span><b>{b.name}</b><small>{b.is_active?'Available throughout the product':'Hidden from new activity'}</small></span><button className="secondary" onClick={()=>toggleBranch(b)}>{b.is_active?'Deactivate':'Activate'}</button></div>)}</div></div>}
    {tab==='staff'&&<div className="settings-card"><div className="settings-section-head"><div><span>ACCESS MANAGEMENT</span><h3>Staff and roles</h3></div></div><form className="staff-create-grid" onSubmit={createStaff}><input required type="email" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})} placeholder="Email address"/><input required value={invite.full_name} onChange={e=>setInvite({...invite,full_name:e.target.value})} placeholder="Full name"/><select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})}><option value="admin">Company Admin</option><option value="staff">Organization Staff</option><option value="branch">Branch Staff</option></select><select value={invite.branch_id} onChange={e=>setInvite({...invite,branch_id:e.target.value})}><option value="">No branch / all permitted</option>{branches.filter(b=>b.is_active).map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><input required minLength="8" type="password" value={invite.password} onChange={e=>setInvite({...invite,password:e.target.value})} placeholder="Temporary password"/><button className="primary" disabled={busy}>Create Staff Account</button></form><div className="settings-staff-table"><div className="head"><span>Name</span><span>Role</span><span>Branch</span><span>Access</span></div>{staff.map(p=><div className="row" key={p.id}><strong>{p.full_name||'Unnamed user'}{p.is_platform_super_admin&&<small>Platform Super Admin</small>}</strong><select disabled={p.is_platform_super_admin} value={p.role||'staff'} onChange={e=>patchStaff(p.id,{role:e.target.value})}><option value="admin">Company Admin</option><option value="staff">Organization Staff</option><option value="branch">Branch Staff</option></select><select disabled={p.is_platform_super_admin} value={p.branch_id||''} onChange={e=>patchStaff(p.id,{branch_id:e.target.value||null})}><option value="">All permitted branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button disabled={p.is_platform_super_admin} className="secondary" onClick={()=>patchStaff(p.id,{is_active:!p.is_active})}>{p.is_active?'Active':'Inactive'}</button></div>)}</div></div>}
    {tab==='modules'&&<form className="settings-card" onSubmit={saveBrand}><div className="settings-section-head"><div><span>PRODUCT CONFIGURATION</span><h3>Enabled modules</h3><p>Web and mobile can read the same list. Core case security remains active even if a module is hidden.</p></div></div><div className="module-settings-grid">{Object.entries(MODULE_LABELS).map(([key,label])=><label key={key} className={settings.enabled_modules.includes(key)?'active':''}><input type="checkbox" checked={settings.enabled_modules.includes(key)} onChange={()=>toggleModule(key)}/><span>{label}</span></label>)}</div><div className="settings-hold"><strong>Automatic WhatsApp</strong><span>Reserved for a later release and forced off in V4.0.</span></div><div className="settings-save"><button className="primary">Save Module Settings</button></div></form>}
    {tab==='companies'&&platform&&<div className="settings-card"><div className="settings-section-head"><div><span>PLATFORM SUPER ADMIN ONLY</span><h3>Companies and installations</h3></div></div><form className="company-create-grid" onSubmit={createOrganization}><input required value={newOrg.name} onChange={e=>setNewOrg({...newOrg,name:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-')})} placeholder="Company name"/><input required value={newOrg.slug} onChange={e=>setNewOrg({...newOrg,slug:e.target.value})} placeholder="company-slug"/><input value={newOrg.legal_name} onChange={e=>setNewOrg({...newOrg,legal_name:e.target.value})} placeholder="Legal name"/><select value={newOrg.deployment_mode} onChange={e=>setNewOrg({...newOrg,deployment_mode:e.target.value})}><option value="Tenant">Shared SaaS tenant</option><option value="Dedicated">Dedicated installation</option></select><input type="email" value={newOrg.contact_email} onChange={e=>setNewOrg({...newOrg,contact_email:e.target.value})} placeholder="Contact email"/><button className="primary">Create Company</button></form><div className="settings-company-grid">{organizations.map(o=><button key={o.id} className={o.id===organizationId?'active':''} onClick={()=>setOrganizationId(o.id)}><strong>{o.name}</strong><span>{o.deployment_mode} · {o.status}</span></button>)}</div>{selectedOrganization&&<div className="company-status-actions"><span>Selected: <b>{selectedOrganization.name}</b></span>{['Active','Suspended','Archived'].map(x=><button type="button" className={selectedOrganization.status===x?'primary':'secondary'} key={x} onClick={()=>updateOrganization({status:x})}>{x}</button>)}</div>}</div>}
  </section>
}
