'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import {userError} from '../lib/userError';
export default function QuickAddRecord({type,orgId,branchId,onClose,onSaved,notify}){
 const [form,setForm]=useState({name:'',mobile:'',email:'',category:'',government_fee:'0',service_charge:'0',service_type:'Sale',stages:''}),[saving,setSaving]=useState(false);const key=useRef(crypto.randomUUID()),pending=useRef(false),root=useRef(null);
 useEffect(()=>{const previous=document.activeElement;root.current?.querySelector('input')?.focus();const handler=e=>{if(e.key==='Escape'&&!pending.current)onClose();if(e.key==='Tab'){const items=[...root.current.querySelectorAll('input,select,textarea,button')].filter(e=>!e.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.isConnected&&previous.focus()}},[]);
 const patch=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function save(e){e.preventDefault();if(pending.current)return;pending.current=true;setSaving(true);try{const input=type==='service'?{organization_id:orgId,...form,government_fee:Number(form.government_fee),service_charge:Number(form.service_charge),workflow:form.stages.split('\n').map(s=>s.trim()).filter(Boolean)}:{organization_id:orgId,branch_id:branchId,name:form.name,mobile:form.mobile,email:form.email};const {data,error}=await supabase.rpc(type==='service'?'quick_add_service':'quick_add_customer',{input,request_key:key.current});if(error)throw error;const {data:record,error:readError}=await supabase.from(type==='service'?'service_catalog':'crm_customers').select('*').eq('organization_id',orgId).eq('id',data).single();if(readError)throw readError;onSaved(record);notify(type==='service'?'Service added and selected.':'Customer added and selected.')}catch(error){notify(userError(error))}finally{pending.current=false;setSaving(false)}}
 return <div className="business-overlay quick-add-overlay"><section ref={root} className="business-dialog business-small-dialog" role="dialog" aria-modal="true" aria-label={`Quick add ${type}`}><header><div><small>QUICK ADD</small><h2>New {type}</h2></div><button disabled={saving} aria-label="Close" className="business-close" onClick={onClose}>×</button></header><form onSubmit={save}><div className="business-form"><label className="wide">{type==='service'?'Service name':'Customer name'}<input required maxLength="200" value={form.name} onChange={e=>patch('name',e.target.value)}/></label>{type==='customer'?<><label>Mobile<input type="tel" value={form.mobile} onChange={e=>patch('mobile',e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>patch('email',e.target.value)}/></label></>:<><label>Government fee<input required type="number" min="0" step=".01" value={form.government_fee} onChange={e=>patch('government_fee',e.target.value)}/></label><label>Service charge<input required type="number" min="0" step=".01" value={form.service_charge} onChange={e=>patch('service_charge',e.target.value)}/></label><label>Category<input value={form.category} onChange={e=>patch('category',e.target.value)}/></label><label>Type<select value={form.service_type} onChange={e=>{patch('service_type',e.target.value);if(e.target.value==='Sale')patch('stages','')}}>{['Sale','Service','Staged service'].map(t=><option key={t}>{t}</option>)}</select></label>{form.service_type!=='Sale'&&<label className="wide">Stages (optional, one per line)<textarea rows="3" value={form.stages} onChange={e=>patch('stages',e.target.value)}/></label>}</>}</div><footer><button type="button" disabled={saving} className="secondary" onClick={onClose}>Cancel</button><button disabled={saving} className="primary">{saving?'Saving…':'Save & select'}</button></footer></form></section></div>
}
