import {createClient} from '@supabase/supabase-js';
import {createHash,createHmac} from 'node:crypto';
import {apiJson,bearerToken,hasLiveSession,consumeRateLimit} from './serverSecurity';
import {checkPortal} from './portalAccess';
import {trackingLink} from './trackingLinks';
export function communicationAdmin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error('Communication service is not configured.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export function workerToken(){const key=process.env.COMMUNICATIONS_WORKER_SECRET||process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY;if(!key)throw new Error('Worker is unavailable.');return createHmac('sha256',key).update('workspace-communications-worker-v5').digest('hex')}
export async function communicationContext(request,organizationId){const token=bearerToken(request);if(!token)return {response:apiJson({error:'Please sign in.',code:'AUTH_REQUIRED'},401)};const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_ANON_KEY;if(!url||!key)return {response:apiJson({error:'Service is unavailable.',code:'NOT_CONFIGURED'},503)};const viewer=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error}=await viewer.auth.getUser(token);if(error||!user||!await hasLiveSession(viewer))return {response:apiJson({error:'Your session has expired. Please sign in again.',code:'INVALID_SESSION'},401)};const admin=communicationAdmin();const {data:profile}=await admin.from('profiles').select('id,organization_id,role,is_active,is_platform_super_admin').eq('id',user.id).maybeSingle();if(!profile?.is_active||profile.role!=='admin')return {response:apiJson({error:'Administrator access is required.',code:'FORBIDDEN'},403)};const denied=await checkPortal(admin,profile,request);if(denied)return {response:denied};const org=profile.is_platform_super_admin?organizationId:profile.organization_id;if(!org||organizationId&&org!==organizationId)return {response:apiJson({error:'Select a company you administer.',code:'FORBIDDEN'},403)};const {data:company}=await admin.from('organizations').select('id,status').eq('id',org).maybeSingle();if(!company||!profile.is_platform_super_admin&&company.status!=='Active')return {response:apiJson({error:'This company is unavailable.',code:'FORBIDDEN'},403)};return {admin,profile,organizationId:org}}
export const hash=value=>createHash('sha256').update(value).digest('hex');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function customerMessage(payload,colors={}){colors=colors||{};const names={case_created:'Case registered',case_status:'Case update',payment:'Payment received',appointment:'Appointment update',delivery:'Delivery confirmation',job_status:'Service update',invoice_issued:'Sales document issued',renewal:'Renewal reminder'};const title=names[payload.event]||'Service update';const link=payload.tracking_base?trackingLink({base:payload.tracking_base,reference:payload.reference}):'';const primary=/^#[a-f\d]{6}$/i.test(colors.primary_color||'')?colors.primary_color:'#3265DF',secondary=/^#[a-f\d]{6}$/i.test(colors.secondary_color||'')?colors.secondary_color:'#17879A';const content=`Hello ${payload.name||'Customer'},\n\n${title}\nReference: ${payload.reference||'—'}\nStatus: ${payload.status||'—'}${payload.amount?`\nAmount received: ${payload.amount}`:''}${payload.date?`\nDate: ${payload.date}`:''}${link?`\nTrack your case: ${link}`:''}\n\n${payload.company||'Your service team'}`;return {subject:`${title} · ${payload.reference||payload.company||'Your service'}`,text:content,link,html:`<!doctype html><html><body style="margin:0;background:#f2f6fc;font-family:Arial,sans-serif;color:#1a2e4a"><main style="max-width:600px;margin:30px auto;background:white;border-radius:20px;overflow:hidden"><header style="padding:30px;background:linear-gradient(120deg,${primary},${secondary});color:white"><b>${esc(payload.company||'Your service team')}</b><h1 style="font-size:25px">${esc(title)}</h1></header><section style="padding:30px"><p>Hello ${esc(payload.name||'Customer')},</p><p>Here is the latest update for your service.</p><table style="width:100%;border-collapse:collapse"><tr><td style="padding:12px;background:#f3f7fd">Reference</td><td style="padding:12px">${esc(payload.reference||'—')}</td></tr><tr><td style="padding:12px;background:#f3f7fd">Status</td><td style="padding:12px">${esc(payload.status||'—')}</td></tr>${payload.amount?`<tr><td style="padding:12px;background:#f3f7fd">Amount received</td><td style="padding:12px">${esc(payload.amount)}</td></tr>`:''}${payload.date?`<tr><td style="padding:12px;background:#f3f7fd">Date</td><td style="padding:12px">${esc(payload.date)}</td></tr>`:''}</table>${link?`<p style="margin-top:28px"><a style="background:${primary};padding:14px 22px;color:white;text-decoration:none;border-radius:10px;display:inline-block" href="${esc(link)}">Track your case</a></p>`:''}<p style="font-size:12px;color:#8491a4;margin-top:28px">Contact your service provider if you no longer wish to receive service updates.</p></section></main></body></html>`}}
function providerRequest(job,cfg,key,message){
 if(job.channel==='whatsapp')return {url:`https://graph.facebook.com/${cfg.whatsapp_api_version}/${cfg.whatsapp_phone_id}/messages`,headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:{messaging_product:'whatsapp',to:job.recipient,type:'template',template:{name:cfg.whatsapp_template,language:{code:cfg.whatsapp_language},components:[{type:'body',parameters:[job.payload.name||'Customer',job.payload.reference||'—',job.payload.status||'Update',message.link||'Contact your service provider'].map(text=>({type:'text',text:String(text).slice(0,1024)}))}]}}};
 if(cfg.email_provider==='brevo')return {url:'https://api.brevo.com/v3/smtp/email',headers:{'api-key':key,'content-type':'application/json',accept:'application/json'},body:{sender:{name:cfg.sender_name||job.payload.company,email:cfg.sender_email},to:[{email:job.recipient,name:job.payload.name}],subject:message.subject,htmlContent:message.html,textContent:message.text,...(cfg.reply_to?{replyTo:{email:cfg.reply_to}}:{})}};
 return {url:'https://api.resend.com/emails',headers:{authorization:`Bearer ${key}`,'content-type':'application/json','Idempotency-Key':`workspace-${job.id}`},body:{from:`${String(cfg.sender_name||job.payload.company||'Service team').replace(/[<>\r\n]/g,'')} <${cfg.sender_email}>`,to:[job.recipient],subject:message.subject,html:message.html,text:message.text,...(cfg.reply_to?{reply_to:cfg.reply_to}:{})}};
}
async function processOne(admin,job,fetcher){
 const {data:cfg,error}=await admin.from('communication_settings').select('*').eq('organization_id',job.organization_id).maybeSingle();if(error)throw error;
 const {data:org}=await admin.from('organizations').select('status').eq('id',job.organization_id).maybeSingle();
 if(!cfg||Array.isArray(cfg.event_types)&&!cfg.event_types.includes(job.event_type)||org?.status!=='Active'||job.channel==='email'&&!cfg.email_enabled||job.channel==='whatsapp'&&!cfg.whatsapp_enabled)return {status:'Skipped',last_error:'Sending is disabled for this company.'};
 const {data:consented,error:consentError}=await admin.rpc('communication_recipient_allowed',{message_id:job.id});if(consentError)throw consentError;if(!consented)return {status:'Skipped',last_error:'Customer permission or contact details changed.'};
 const {data:secrets,error:secretError}=await admin.rpc('get_communication_credentials',{target_org:job.organization_id,credential_kind:job.channel});if(secretError)throw secretError;
 const key=job.channel==='email'?secrets?.api_key:secrets?.access_token;
 if(!key)return {status:'Failed',last_error:'Provider credentials are missing.'};
 const limits=job.channel==='email'?(cfg.email_provider==='brevo'?{day:300,month:100000}:{day:100,month:3000}):{day:cfg.whatsapp_daily_limit,month:10000000};
 const {data:reserved,error:reserveError}=await admin.rpc('reserve_communication_quota',{account_hash:hash(`${job.channel}:${key}`),company_hash:hash(`${job.organization_id}:${job.channel}`),daily_cap:limits.day,monthly_cap:limits.month,company_daily_cap:job.channel==='email'?Math.min(cfg.email_daily_limit,limits.day):cfg.whatsapp_daily_limit,company_monthly_cap:job.channel==='email'?Math.min(cfg.email_monthly_limit,limits.month):10000000});if(reserveError)throw reserveError;
 if(!reserved)return {status:'Queued',attempts:Math.max(0,job.attempts-1),last_error:'Free sending limit reached. Waiting for the next quota window.',next_attempt:new Date(Date.now()+24*60*60*1000).toISOString()};
 const {data:brand}=await admin.from('organization_settings').select('primary_color,secondary_color').eq('organization_id',job.organization_id).maybeSingle();
 const request=providerRequest(job,cfg,key,customerMessage(job.payload,brand));let response;
 try{response=await fetcher(request.url,{method:'POST',headers:request.headers,body:JSON.stringify(request.body),signal:AbortSignal.timeout(12000),redirect:'error'})}catch{return {status:'Unconfirmed',last_error:'The provider response was interrupted. Review provider logs before sending again.'}}
 const data=await response.json().catch(()=>({}));
 if(response.ok)return {status:'Accepted',provider_message_id:data.messageId||data.id||data.messages?.[0]?.id||null,last_error:null};
 if((response.status===429||response.status>=500&&job.channel==='email'&&cfg.email_provider==='resend')&&job.attempts<5)return {status:'Queued',last_error:'Provider temporarily unavailable. A retry is scheduled.',next_attempt:new Date(Date.now()+Math.min(3600,60*2**job.attempts)*1000).toISOString()};
 if(response.status>=500)return {status:'Unconfirmed',last_error:'The provider returned a server error. Review its logs before resending.'};
 return {status:'Failed',last_error:`Provider rejected the request (HTTP ${response.status}). Check the sender, template and credentials.`};
}
export async function processCommunications(admin,organizationId=null,{fetcher=fetch}={}){
 const {data:jobs,error}=await admin.rpc('claim_communications',{target_org:organizationId});if(error)throw error;
 const result={accepted:0,failed:0,deferred:0,unconfirmed:0};
 for(const job of jobs||[]){let outcome;
  try{outcome=await processOne(admin,job,fetcher)}catch(error){console.error('Communication processing failed',{job_id:job.id,code:error?.code||'PROCESSING_ERROR'});outcome={status:'Unconfirmed',last_error:'Sending could not be completed. Review the provider logs before retrying.'}}
  const category={Accepted:'accepted',Failed:'failed',Queued:'deferred',Unconfirmed:'unconfirmed'}[outcome.status];if(category)result[category]++;
  const {error:updateError}=await admin.from('communication_outbox').update({...outcome,updated_at:new Date().toISOString()}).eq('id',job.id).eq('status','Processing');if(updateError)console.error('Communication result could not be saved',{job_id:job.id,code:updateError.code});
 }
 return result;
}
export async function communicationRate(admin,id,bucket='communications-admin'){return consumeRateLimit(admin,{bucket,key:id,limit:60,windowSeconds:3600})}
