import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),root=path.resolve('lib'),cache=new Map();
async function compiled(file){const filename=path.resolve(file);if(cache.has(filename))return cache.get(filename);const {code}=await require('next/dist/build/swc').transform(fs.readFileSync(filename,'utf8'),{filename,jsc:{parser:{syntax:'ecmascript'},target:'es2022'},module:{type:'commonjs'}});const modules=new Map();for(const m of code.matchAll(/require\("(\.[^"]+)"\)/g)){const candidate=path.resolve(path.dirname(filename),m[1])+'.js';if(fs.existsSync(candidate))modules.set(m[1],await compiled(candidate))}const module={exports:{}};new Function('require','module','exports',code)(name=>modules.has(name)?modules.get(name):require(name),module,module.exports);cache.set(filename,module.exports);return module.exports}
const {processCommunications,customerMessage}=await compiled(path.join(root,'communicationsServer.js'));let checks=0;
const base={id:'test-message',organization_id:'company-a',channel:'email',recipient:'customer@example.test',attempts:1,payload:{company:'Example Company',name:'<script>unsafe</script>',reference:'10025',status:'Received',event:'case_created',tracking_base:'https://example.test/track/'}};
function mockAdmin({job=base,cfg={email_enabled:true,email_provider:'resend',sender_name:'Company',sender_email:'updates@example.test',email_daily_limit:100,email_monthly_limit:3000},reserved=true,active=true}={}){const updates=[];return {updates,rpc:async(name)=>({data:name==='claim_communications'?[job]:name==='get_communication_credentials'?{api_key:'fixture-provider-value',access_token:'fixture-access-value'}:name==='reserve_communication_quota'?reserved:name==='communication_recipient_allowed'?true:null}),from:table=>{let patch;const chain={select:()=>chain,eq:()=>chain,update:p=>{patch=p;return chain},maybeSingle:async()=>({data:table==='communication_settings'?cfg:table==='organizations'?{status:active?'Active':'Suspended'}:{primary_color:'#123456',secondary_color:'#654321'}}),then:resolve=>{if(patch)updates.push(patch);return Promise.resolve(resolve({data:[],error:null}))}};return chain}}}
const message=customerMessage(base.payload,{primary_color:'bad" onclick="evil'});assert.ok(!message.html.includes('<script>unsafe'));assert.ok(message.html.includes('&lt;script&gt;'));assert.equal(message.link,'https://example.test/track/10025');checks+=3;
let sent=0;const a=mockAdmin();const good=await processCommunications(a,null,{fetcher:async(url,opts)=>{sent++;assert.equal(url,'https://api.resend.com/emails');assert.equal(opts.headers['Idempotency-Key'],'workspace-test-message');assert.equal(JSON.parse(opts.body).to[0],base.recipient);return {ok:true,status:200,json:async()=>({id:'provider-id'})}}});assert.equal(good.accepted,1);assert.equal(a.updates[0].status,'Accepted');checks+=5;
const cap=mockAdmin({reserved:false});await processCommunications(cap,null,{fetcher:()=>{throw new Error('Must not send')}});assert.equal(cap.updates[0].status,'Queued');assert.equal(cap.updates[0].attempts,0);checks+=2;
const off=mockAdmin({active:false});await processCommunications(off,null,{fetcher:()=>{throw new Error('Must not send')}});assert.equal(off.updates[0].status,'Skipped');checks++;
const timeout=mockAdmin();await processCommunications(timeout,null,{fetcher:async()=>{throw new Error('Timeout')}});assert.equal(timeout.updates[0].status,'Unconfirmed');checks++;
const rate=mockAdmin();await processCommunications(rate,null,{fetcher:async()=>({ok:false,status:429,json:async()=>({error:'provider secret details'})})});assert.equal(rate.updates[0].status,'Queued');assert.ok(!rate.updates[0].last_error.includes('secret'));checks+=2;
const wa=mockAdmin({job:{...base,channel:'whatsapp',recipient:'97412345678'},cfg:{whatsapp_enabled:true,whatsapp_phone_id:'1234567',whatsapp_template:'service_update',whatsapp_language:'en',whatsapp_api_version:'v25.0',whatsapp_daily_limit:50}});await processCommunications(wa,null,{fetcher:async(url,opts)=>{assert.equal(url,'https://graph.facebook.com/v25.0/1234567/messages');assert.equal(JSON.parse(opts.body).template.components[0].parameters.length,4);return {ok:false,status:500,json:async()=>({})}}});assert.equal(wa.updates[0].status,'Unconfirmed');checks+=3;
const db=new PGlite();const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
try{
 await db.exec(`create role postgres superuser;set session authorization postgres;create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');create table auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create function auth.uid() returns uuid language sql stable as $$select nullif(auth.jwt()->>'sub','')::uuid$$;create function auth.role() returns text language sql stable as $$select auth.jwt()->>'role'$$;grant usage on schema public,auth to anon,authenticated,service_role;grant execute on all functions in schema auth to authenticated,service_role;`);
 await db.exec(fs.readFileSync(new URL('../supabase/V4_0_CLEAN_INSTALL.sql',import.meta.url),'utf8').replace('create extension if not exists pgcrypto;',''));
 await db.exec(fs.readFileSync(new URL('../supabase/V5_1_COMMUNICATIONS.sql',import.meta.url),'utf8'));
 await db.query("insert into organizations(id,name,slug) values($1,'Test Company','test')",[id(1)]);await db.query("insert into organization_settings(organization_id,company_name,tracking_base_url) values($1,'Test Company','https://example.test/track/')",[id(1)]);await db.query("insert into branches(id,organization_id,name) values($1,$2,'Branch')",[id(11),id(1)]);
 await db.query("insert into communication_settings(organization_id,email_enabled,whatsapp_enabled) values($1,true,true)",[id(1)]);
 await db.query("insert into cases(id,organization_id,branch_id,tracking_reference,customer_name,customer_email,mobile,notes) values($1,$2,$3,'10025','Customer','customer@example.test','12345678','Internal secret note')",[id(31),id(1),id(11)]);
 assert.equal((await db.query('select count(*) n from communication_outbox')).rows[0].n,0);checks++;
 await db.query("update cases set email_updates=true,whatsapp_opt_in=true,overall_status='Under Process' where id=$1",[id(31)]);assert.equal((await db.query('select count(*) n from communication_outbox')).rows[0].n,2);checks++;
 const payload=(await db.query("select payload::text from communication_outbox limit 1")).rows[0].payload;assert.ok(!payload.includes('Internal secret note'));checks++;
 await db.query("update cases set notes='Changed internal note' where id=$1",[id(31)]);assert.equal((await db.query('select count(*) n from communication_outbox')).rows[0].n,2);checks++;
 await db.query("insert into payments(organization_id,case_id,amount,payment_method) values($1,$2,50,'Cash')",[id(1),id(31)]);assert.equal((await db.query('select count(*) n from communication_outbox')).rows[0].n,4);checks++;
 await db.query("insert into appointments(organization_id,case_id,appointment_date) values($1,$2,current_date)",[id(1),id(31)]);checks++;
 await db.query("insert into deliveries(organization_id,case_id,status) values($1,$2,'Partial')",[id(1),id(31)]);checks++;
 const consentId=(await db.query("select id from communication_outbox where channel='email' limit 1")).rows[0].id;assert.equal((await db.query('select communication_recipient_allowed($1) ok',[consentId])).rows[0].ok,true);await db.query('update cases set email_updates=false where id=$1',[id(31)]);assert.equal((await db.query('select communication_recipient_allowed($1) ok',[consentId])).rows[0].ok,false);checks+=2;
 const h1='a'.repeat(64),h2='b'.repeat(64),h3='c'.repeat(64);assert.equal((await db.query('select reserve_communication_quota($1,$2,1,10,10,10) ok',[h1,h2])).rows[0].ok,true);assert.equal((await db.query('select reserve_communication_quota($1,$2,1,10,10,10) ok',[h1,h3])).rows[0].ok,false);checks+=2;
 const claimed=(await db.query('select id from claim_communications(null)')).rows;assert.equal(claimed.length,3);const claimed2=(await db.query('select id from claim_communications(null)')).rows;assert.ok(claimed2.every(r=>!claimed.some(c=>c.id===r.id)));checks+=2;
 await db.exec("update communication_outbox set updated_at=now()-interval '10 minutes' where status='Processing';select * from claim_communications(null)");assert.ok((await db.query("select count(*) n from communication_outbox where status='Unconfirmed'")).rows[0].n>=3);checks++;
 await db.exec('set role authenticated');await assert.rejects(()=>db.query('select * from integration_credentials'));await assert.rejects(()=>db.query('select get_communication_credentials($1,$2)',[id(1),'email']));await assert.rejects(()=>db.query('select * from communication_runtime'));await assert.rejects(()=>db.query('select * from claim_communications(null)'));checks+=4;
 console.log(`PASS: ${checks} communication assertions; no real provider messages sent. Consent, field privacy, quota caps, worker isolation and uncertain outcomes tested.`);
}finally{await db.close()}
